In [1]:
import numpy as np
import pandas as pd

In [2]:
twitter_df = pd.read_csv('./dataset/twitter_training.csv')
twitter_df.head()

2401  Borderlands  Positive  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

  im getting on borderlands and i will murder you all ,  
0  I am coming to the borders and I will kill you...     
1  im getting on borderlands and i will kill you ...     
2  im coming on borderlands and i will murder you...     
3  im getting on borderlands 2 and i will murder ...     
4  im getting into borderlands and i can murder y...

In [56]:
dff = pd.read_csv('./imdb_data/IMDB Dataset.csv')
dff.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
dff['review'][100].lower()

"this short film that inspired the soon-to-be full length feature - spatula madness - is a hilarious piece that contends against similar cartoons yielding multiple writers. the short film stars edward the spatula who after being fired from his job, joins in the fight against the evil spoons. this premise allows for some funny content near the beginning, but is barely present for the remainder of the feature. this film's 15-minute running time is absorbed by some odd-ball comedy and a small musical number. unfortunately not much else lies below it. the plot that is set up doesn't really have time to show. but it's surely follows it plot better than many high-budget hollywood films. this film is worth watching at least a few times. take it for what it is, and don't expect a deep story."

In [5]:
dff['review'] = dff['review'].str.lower()

In [6]:
import re

def remove_html_tags(text):
  pattern= re.compile('<.*?>')
  return pattern.sub('', text)

In [7]:
dff['review'] = dff['review'].apply(remove_html_tags)
dff.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [8]:
chat_word = {
    'AFAIK': 'As Far As I Know',
    'AFK': 'Away From Keyboard',
    'ASAP': 'As Soon As Possible',
    'ATK': 'At The Keyboard',
    'ATM': 'At The Moment',
    'A3': 'Anytime, Anywhere, Anyplace',
    'BAK': 'Back At Keyboard',
    'BBL': 'Be Back Later',
    'BBS': 'Be Back Soon',
    'BFN': 'Bye For Now',
    'B4N': 'Bye For Now',
    'BRB': 'Be Right Back',
    'BRT': 'Be Right There',
    'BTW': 'By The Way',
    'B4': 'Before',
    'CU': 'See You',
    'CUL8R': 'See You Later',
    'CYA': 'See You',
    'FAQ': 'Frequently Asked Questions',
    'FC': 'Fingers Crossed',
    'FWIW': "For What It's Worth",
    'FYI': 'For Your Information',
    'GAL': 'Get A Life',
    'GG': 'Good Game',
    'GN': 'Good Night',
    'GMTA': 'Great Minds Think Alike',
    'GR8': 'Great!',
    'G9': 'Genius',
    'IC': 'I See',
    'ICQ': 'I Seek you (also a chat program)',
    'ILU': 'ILU: I Love You',
    'IMHO': 'In My Honest/Humble Opinion',
    'IMO': 'In My Opinion',
    'IOW': 'In Other Words',
    'IRL': 'In Real Life',
    'KISS': 'Keep It Simple, Stupid',
    'LDR': 'Long Distance Relationship',
    'LMAO': 'Laugh My A.. Off',
    'LOL': 'Laughing Out Loud',
    'LTNS': 'Long Time No See',
    'L8R': 'Later',
    'MTE': 'My Thoughts Exactly',
    'M8': 'Mate',
    'NRN': 'No Reply Necessary',
    'OIC': 'Oh I See',
    'PITA': 'Pain In The A..',
    'PRT': 'Party',
    'PRW': 'Parents Are Watching',
    'QPSA?': 'Que Pasa?',
    'ROFL': 'Rolling On The Floor Laughing',
    'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
    'ROTFLMAO': 'Rolling On The Floor Laughing My A.. Off',
    'SK8': 'Skate',
    'STATS': 'Your sex and age',
    'ASL': 'Age, Sex, Location',
    'THX': 'Thank You',
    'TTFN': 'Ta-Ta For Now!',
    'TTYL': 'Talk To You Later',
    'U': 'You',
    'U2': 'You Too',
    'U4E': 'Yours For Ever',
    'WB': 'Welcome Back',
    'WTF': 'What The F...',
    'WTG': 'Way To Go!',
    'WUF': 'Where Are You From?',
    'W8': 'Wait...',
    '7K': 'Sick:-D Laugher',
    'TFW': 'That feeling when',
    'MFW': 'My face when',
    'MRW': 'My reaction when',
    'IFYP': 'I feel your pain',
    'TNTL': 'Trying not to laugh',
    'JK': 'Just kidding',
    'IDC': "I don't care",
    'ILY': 'I love you',
    'IMU': 'I miss you',
    'ADIH': 'Another day in hell',
    'ZZZ': 'Sleeping, bored, tired',
    'WYWH': 'Wish you were here',
    'TIME': 'Tears in my eyes',
    'BAE': 'Before anyone else',
    'FIMH': 'Forever in my heart',
    'BSAAW': 'Big smile and a wink',
    'BWL': 'Bursting with laughter',
    'BFF': 'Best friends forever',
    'CSL': "Can't stop laughing"
}

In [9]:
def short_conv(text):
  new_text= []
  for w in text.split():
    if w.upper() in chat_word:
      new_text.append(chat_word[w.upper()])
    else:
      new_text.append(w)
  return ' '.join(new_text)

short_conv("ASAP let me know please")

'As Soon As Possible let me know please'

In [10]:
pip install autocorrect

Note: you may need to restart the kernel to use updated packages.


In [11]:
from autocorrect import Speller

spell = Speller(lang="en")  # English spell checker
text = " ceertainli I dont kniw what is wrrong herre"
corrected_text = spell(text)

print(corrected_text)

 certainly I dont know what is wrong here


In [12]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

STOPWORDS = set(stopwords.words('english'))
def remove_stop_words(text):
  return ' '.join([word for word in str(text).split() if word not in STOPWORDS])

[nltk_data] Downloading package stopwords to C:\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [13]:
text="I wasn't sure that this might happened"
remove_stop_words(text)

'I sure might happened'

In [14]:
import spacy

nlp = spacy.load('en_core_web_sm')

sentence = "The children were playing in the park, running and laughing as they enjoyed their freedom, unaware of the time passing quickly by."
doc = nlp(sentence)

for toke in doc:
  print(f'{toke.text} = {toke.lemma_}')

The = the
children = child
were = be
playing = play
in = in
the = the
park = park
, = ,
running = run
and = and
laughing = laugh
as = as
they = they
enjoyed = enjoy
their = their
freedom = freedom
, = ,
unaware = unaware
of = of
the = the
time = time
passing = pass
quickly = quickly
by = by
. = .


In [15]:
from sklearn.preprocessing import OneHotEncoder

data = { 'ID':[1,2,3,4,5], 'Color':['red','green','blue','green','blue']}
data_df = pd.DataFrame(data)
data_df

ID  Color
0   1    red
1   2  green
2   3   blue
3   4  green
4   5   blue

In [16]:
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data_df[['Color']])
encoded_df = pd.DataFrame(encoded_data.toarray(), columns= encoder.get_feature_names_out(['Color']))
final_df = pd.concat([data_df, encoded_df], axis=1)
final_df

ID  Color  Color_blue  Color_green  Color_red
0   1    red         0.0          0.0        1.0
1   2  green         0.0          1.0        0.0
2   3   blue         1.0          0.0        0.0
3   4  green         0.0          1.0        0.0
4   5   blue         1.0          0.0        0.0

In [17]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [18]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [19]:
import gensim.downloader


glove_vectors = gensim.downloader.load('glove-twitter-25')

In [20]:
glove_vectors['books']

array([ 0.64268  ,  0.045608 ,  1.0344   , -0.2208   ,  0.73695  ,
       -0.83979  ,  1.3606   , -1.417    ,  0.02012  , -0.91255  ,
        0.11603  ,  0.24853  , -3.7822   , -0.21286  , -0.13444  ,
       -0.1682   ,  0.70644  ,  0.10234  ,  0.42941  ,  0.21326  ,
       -0.83451  , -1.1294   , -1.0398   ,  0.25531  ,  0.0081801],
      dtype=float32)

In [21]:
glove_vectors.most_similar('books')

[('book', 0.94181889295578),
 ('stories', 0.9077752828598022),
 ('added', 0.8998989462852478),
 ('script', 0.8935744762420654),
 ('reference', 0.8861762285232544),
 ('feature', 0.8841565251350403),
 ('shared', 0.8795639276504517),
 ('included', 0.8661485910415649),
 ('features', 0.8640419840812683),
 ('reading', 0.860645592212677)]

In [22]:
glove_vectors.doesnt_match(['book', 'teacher', 'school', 'woman'])

'woman'

In [23]:
glove_vectors.similarity('dog', 'cat')

0.959082

In [57]:
full_df = dff.iloc[:15000]
full_df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [58]:
full_df.size

30000

In [59]:
full_df.duplicated().sum()

39

In [60]:
df = full_df.drop_duplicates()
df.shape

(14961, 2)

In [ ]:
import re
from nltk.corpus import stopwords

def remove_html_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text
df['review'] = df['review'].apply(remove_html_tags)

sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: ' '.join(x))

df['review'] = df['review'].apply(lambda x : x.lower())

df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13272\517060885.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_html_tags)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13272\517060885.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x: ' '.join(x))
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13272\517060885.py:14: SettingWithCopyWarning: 
A value is trying to

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought wonderful way spend time hot summer ...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
14995  bobcat goldthwait commended attempting somethi...  negative
14996  and since days "clarissa explains it all" i've...  positive
14997  a traveling couple (horton hamilton)stumble on...  negative
14998  this film deeply disappointing. not wenders di...  negative
14999  the revelation lana turner's dancing ability. ...  positive

[14961 rows x 2 columns]

In [62]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [63]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 1])

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train.shape

(11968, 1)

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

X_train_bow.shape

(11968, 57305)

In [66]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train_bow, y_train)

GaussianNB()

In [67]:
y_pred = gnb.predict(X_test_bow)

In [70]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy_score(y_pred, y_test)

0.6625459405278984

In [69]:
confusion_matrix(y_test, y_pred)

array([[1144,  359],
       [ 651,  839]], dtype=int64)

In [72]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8509856331440027